# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee18cd955098dc742295d287ef48ff0e4c04721261fc0836652e3d36e9f330383605e59cd242470cc0ea42326200303a9cb20c4c2390a400517155e2630cabdd

test:
  secret_key_base: 0029dbbac453e6f11bde1a9b5c8d7057a1100c6cd493d02c45e771805cb1166bc41c8837fc5953abf9cdcaf2984aa080f2d09ff3febdb947eb03a36d88575b6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
